=== LLuke/xerlin/examples/personal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

 <xs:element name="personnel">
  <xs:annotation>
    <xs:documentation>
	<b><font color="blue">Personnel Details</font></b><br/>
	<i>This file contains details about personnel.</i><br/>
      To add another <code>person</code> to the file, right click
      on <code>personnel</code> in the tree.<br/>
      To display documentation like this, add an annotation to your 
      element declaration in the XSD.
    </xs:documentation>
  </xs:annotation>
  <xs:complexType>
    <xs:annotation>
        <xs:documentation xml:lang="en">
        Must contain a person
        </xs:documentation>
    </xs:annotation>
   <xs:sequence>
     <xs:element ref="person" minOccurs='1' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>

  <xs:unique name="unique1">
   <xs:selector xpath="person"/>
   <xs:field xpath="name/given"/>
   <xs:field xpath="name/family"/>
  </xs:unique>
  <xs:key name='empid'>
   <xs:selector xpath="person"/>
   <xs:field xpath="@id"/>
  </xs:key>
  <xs:keyref name="keyref1" refer='empid'>
   <xs:selector xpath="person"/> 
   <xs:field xpath="link/@manager"/>  
  </xs:keyref>
  <xs:keyref name="spouse-keyref" refer='unique1'>
   <xs:selector xpath="person"/> 
   <xs:field xpath="spouse/@first-name"/>
   <xs:field xpath="spouse/@last-name"/>  
  </xs:keyref>

 </xs:element>

 <xs:element name="person">
  <xs:annotation>
    <xs:documentation>
	<b><font color="blue">Person Details</font></b><br/>
	<i>This element contains details about a person.</i><br/>
    </xs:documentation>
  </xs:annotation>
  <xs:complexType mixed="true">
   <xs:sequence>
     <xs:element ref="name"/>
     <xs:element ref="email" minOccurs='0' maxOccurs='unbounded'/>
     <xs:element ref="url"   minOccurs='0' maxOccurs='unbounded'/>
     <xs:element ref="link"  minOccurs='0' maxOccurs='1'/>
     <xs:element ref="spouse" minOccurs='0' maxOccurs='1'/>
   </xs:sequence>
   <xs:attribute name="id"  type="xs:ID" use='required'/>
   <xs:attribute name="note">
     <xs:simpleType>
       <xs:restriction base="xs:string">
         <xs:maxLength value="256"/>
       </xs:restriction>
     </xs:simpleType>
   </xs:attribute>
   <xs:attribute name="contr" default="false">
    <xs:simpleType>
     <xs:restriction base = "xs:string">
       <xs:enumeration value="true"/>
       <xs:enumeration value="false"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
   <xs:attribute name="salary" type="xs:integer" default="0"/>
  </xs:complexType>
 </xs:element>

 <xs:element name="name">
  <xs:complexType>
   <xs:all>
    <xs:element ref="family"/>
    <xs:element ref="given"/>
   </xs:all>
  </xs:complexType>
 </xs:element>

 <xs:element name="family" type='xs:string'/>

 <xs:element name="given" type='xs:string'/>

 <xs:element name="email" type='xs:string'/>

 <xs:element name="url">
  <xs:complexType>
   <xs:attribute name="href" type="xs:string" default="http://"/>
  </xs:complexType>
 </xs:element>

 <xs:element name="link">
  <xs:complexType>
   <xs:attribute name="manager" type="xs:IDREF" use="optional"/>
   <xs:attribute name="subordinates" type="xs:IDREFS"/>
  </xs:complexType>
 </xs:element>

 <xs:element name="spouse">
  <xs:complexType>
   <xs:attribute name="first-name" type="xs:string"/>
   <xs:attribute name="last-name" type="xs:string"/>
  </xs:complexType>
 </xs:element>

<xs:notation name='gif' public='-//APP/Photoshop/4.0' system='photoshop.exe'/>

</xs:schema>

=== LLuke/xerlin/examples/personal-schema.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<personnel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personal.xsd">
  <person contr="false" id="Big.Boss" note="This is a note." salary="$100">
    <name>
      <family>Boss</family>
      <given>Big</given>
    </name>
    <link subordinates="one.worker two.worker three.worker four.worker five.worker"/>
    <email>chief@foo.com</email>
  </person>
  <person contr="false" id="one.worker" salary="0">
    <name>
      <family>Worker</family>
      <given>One</given>
    </name>
    <email>one@foo.com</email>
    <link manager="Big.Boss" subordinates="two.worker"/>
    <spouse first-name="One" last-name="Boss"/>
  </person>
  <person contr="false" id="one.worker" salary="0">
    <name>
      <family>Worker</family>
      <given>Two</given>
    </name>
    <email>two@foo.com</email>
    <link manager="Big.Boss" subordinates="three.worker"/>
  </person>
  <person contr="false" id="three.worker" salary="0">
    <name>
      <family>Worker</family>
      <given>Three</given>
    </name>
    <email>three@foo.com</email>
    <link manager="Big.Boss" subordinates="four.worker"/>
  </person>
  <person contr="false" id="four.worker" salary="0">
    <name>
      <family>Worker</family>
      <given>Four</given>
    </name>
    <email>four@foo.com</email>
    <link manager="Big.Boss" subordinates="five.worker"/>
  </person>
  <person contr="false" id="five.worker" salary="0">
    <name>
      <family>Worker</family>
      <given>Five</given>
    </name>
    <email>five@foo.com</email>
    <link manager="Big.Boss"/>
  </person>
  <person contr="false" id="jdkj" salary="0"/>
</personnel>
